"""ctstage_name, sweet_name

Revision ID: 39450e7bbfb3
Revises: 8bc4f9e35b16
Create Date: 2025-07-09 21:22:32.329929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39450e7bbfb3'
down_revision: Union[str, None] = '8bc4f9e35b16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('ctstage_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('sweet_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('is_sv', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_sv')
    op.drop_column('users', 'sweet_name')
    op.drop_column('users', 'ctstage_name')
    # ### end Alembic commands ###