"""Make approver_id required in revisions table

Revision ID: 1483b3da07bd
Revises: dcf8466452cd
Create Date: 2025-08-04 09:50:21.396627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1483b3da07bd'
down_revision = 'dcf8466452cd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Skip this migration - we're keeping approver_id as nullable
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Skip this migration - we're keeping approver_id as nullable
    pass
    # ### end Alembic commands ###