"""Make approver_id required in revisions table

Revision ID: 1483b3da07bd
Revises: dcf8466452cd
Create Date: 2025-08-04 09:50:21.396627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1483b3da07bd'
down_revision = 'dcf8466452cd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('revisions', 'approver_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint('revisions_approver_id_fkey', 'revisions', type_='foreignkey')
    op.create_foreign_key(None, 'revisions', 'users', ['approver_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'revisions', type_='foreignkey')
    op.create_foreign_key('revisions_approver_id_fkey', 'revisions', 'users', ['approver_id'], ['id'], ondelete='SET NULL')
    op.alter_column('revisions', 'approver_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###