"""Schemas Date

Revision ID: 1e7fb0c9beab
Revises: 1483b3da07bd
Create Date: 2025-08-05 12:27:01.378579

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e7fb0c9beab'
down_revision = '1483b3da07bd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###