"""Make approver_id nullable in revisions table

Revision ID: 3f86054cca98
Revises: 1e7fb0c9beab
Create Date: 2025-08-30 21:20:40.425327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f86054cca98'
down_revision = '1e7fb0c9beab'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('revisions', 'approver_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint('revisions_approver_id_fkey', 'revisions', type_='foreignkey')
    op.create_foreign_key(None, 'revisions', 'users', ['approver_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'revisions', type_='foreignkey')
    op.create_foreign_key('revisions_approver_id_fkey', 'revisions', 'users', ['approver_id'], ['id'], ondelete='CASCADE')
    op.alter_column('revisions', 'approver_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###