"""Add approval_group_id to revisions table

Revision ID: 63a5626073be
Revises: 685e3378384d
Create Date: 2025-09-04 20:28:31.507475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63a5626073be'
down_revision = '685e3378384d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('revisions', sa.Column('approval_group_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_revisions_approval_group_id'), 'revisions', ['approval_group_id'], unique=False)
    op.create_foreign_key(None, 'revisions', 'approval_groups', ['approval_group_id'], ['group_id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'revisions', type_='foreignkey')
    op.drop_index(op.f('ix_revisions_approval_group_id'), table_name='revisions')
    op.drop_column('revisions', 'approval_group_id')
    # ### end Alembic commands ###