"""Add submitted_at field to revisions table

Revision ID: 685e3378384d
Revises: acb8ff9afa9b
Create Date: 2025-09-03 20:08:42.732184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '685e3378384d'
down_revision = 'acb8ff9afa9b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('revisions', sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True))
    
    # Set initial values for existing submitted revisions
    # For existing 'submitted', 'approved', or 'rejected' revisions, use created_at as submitted_at
    op.execute("""
        UPDATE revisions 
        SET submitted_at = created_at 
        WHERE status IN ('submitted', 'approved', 'rejected') 
        AND submitted_at IS NULL
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('revisions', 'submitted_at')
    # ### end Alembic commands ###