"""Add foreign key relationship between revisions and articles

Revision ID: acb8ff9afa9b
Revises: 3f86054cca98
Create Date: 2025-08-31 11:00:05.850073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'acb8ff9afa9b'
down_revision = '3f86054cca98'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'revisions', 'articles', ['target_article_id'], ['article_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'revisions', type_='foreignkey')
    # ### end Alembic commands ###