"""create all tables

Revision ID: b0964a48ee11
Revises: 
Create Date: 2025-08-02 00:40:13.852845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0964a48ee11'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approval_groups',
    sa.Column('group_id', sa.String(length=50), nullable=False),
    sa.Column('group_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('group_id')
    )
    op.create_index(op.f('ix_approval_groups_is_active'), 'approval_groups', ['is_active'], unique=False)
    op.create_table('info_categories',
    sa.Column('category_id', sa.String(length=50), nullable=False),
    sa.Column('category_name', sa.String(length=100), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('category_id')
    )
    op.create_index(op.f('ix_info_categories_is_active'), 'info_categories', ['is_active'], unique=False)
    op.create_table('articles',
    sa.Column('article_id', sa.String(length=100), nullable=False),
    sa.Column('article_pk', sa.String(length=200), nullable=False),
    sa.Column('article_number', sa.String(length=100), nullable=False),
    sa.Column('article_url', sa.Text(), nullable=True),
    sa.Column('approval_group', sa.String(length=50), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('info_category', sa.String(length=50), nullable=True),
    sa.Column('keywords', sa.Text(), nullable=True),
    sa.Column('importance', sa.Boolean(), nullable=True),
    sa.Column('publish_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('publish_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('target', sa.String(length=100), nullable=True),
    sa.Column('question', sa.Text(), nullable=True),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('additional_comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['approval_group'], ['approval_groups.group_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['info_category'], ['info_categories.category_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('article_id')
    )
    op.create_index(op.f('ix_articles_approval_group'), 'articles', ['approval_group'], unique=False)
    op.create_index(op.f('ix_articles_article_number'), 'articles', ['article_number'], unique=False)
    op.create_index(op.f('ix_articles_article_pk'), 'articles', ['article_pk'], unique=False)
    op.create_index(op.f('ix_articles_info_category'), 'articles', ['info_category'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('sweet_name', sa.String(length=50), nullable=True),
    sa.Column('ctstage_name', sa.String(length=50), nullable=True),
    sa.Column('role', sa.String(length=20), server_default='user', nullable=False),
    sa.Column('approval_group_id', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['approval_group_id'], ['approval_groups.group_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_approval_group_id'), 'users', ['approval_group_id'], unique=False)
    op.create_index(op.f('ix_users_ctstage_name'), 'users', ['ctstage_name'], unique=True)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_index(op.f('ix_users_sweet_name'), 'users', ['sweet_name'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('revisions',
    sa.Column('revision_id', sa.UUID(), nullable=False),
    sa.Column('target_article_id', sa.String(length=100), nullable=False),
    sa.Column('target_article_pk', sa.String(length=200), nullable=False),
    sa.Column('proposer_id', sa.UUID(), nullable=False),
    sa.Column('after_title', sa.Text(), nullable=True),
    sa.Column('after_info_category', sa.String(length=50), nullable=True),
    sa.Column('after_keywords', sa.Text(), nullable=True),
    sa.Column('after_importance', sa.Boolean(), nullable=True),
    sa.Column('after_publish_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('after_publish_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('after_target', sa.String(length=100), nullable=True),
    sa.Column('after_question', sa.Text(), nullable=True),
    sa.Column('after_answer', sa.Text(), nullable=True),
    sa.Column('after_additional_comment', sa.Text(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='draft', nullable=False),
    sa.Column('approver_id', sa.UUID(), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['after_info_category'], ['info_categories.category_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['approver_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['proposer_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('revision_id')
    )
    op.create_index(op.f('ix_revisions_approver_id'), 'revisions', ['approver_id'], unique=False)
    op.create_index(op.f('ix_revisions_created_at'), 'revisions', ['created_at'], unique=False)
    op.create_index(op.f('ix_revisions_proposer_id'), 'revisions', ['proposer_id'], unique=False)
    op.create_index(op.f('ix_revisions_status'), 'revisions', ['status'], unique=False)
    op.create_index(op.f('ix_revisions_target_article_id'), 'revisions', ['target_article_id'], unique=False)
    op.create_table('simple_notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('revision_id', sa.UUID(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['revision_id'], ['revisions.revision_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_simple_notifications_created_at'), 'simple_notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_simple_notifications_is_read'), 'simple_notifications', ['is_read'], unique=False)
    op.create_index(op.f('ix_simple_notifications_type'), 'simple_notifications', ['type'], unique=False)
    op.create_index(op.f('ix_simple_notifications_user_id'), 'simple_notifications', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_simple_notifications_user_id'), table_name='simple_notifications')
    op.drop_index(op.f('ix_simple_notifications_type'), table_name='simple_notifications')
    op.drop_index(op.f('ix_simple_notifications_is_read'), table_name='simple_notifications')
    op.drop_index(op.f('ix_simple_notifications_created_at'), table_name='simple_notifications')
    op.drop_table('simple_notifications')
    op.drop_index(op.f('ix_revisions_target_article_id'), table_name='revisions')
    op.drop_index(op.f('ix_revisions_status'), table_name='revisions')
    op.drop_index(op.f('ix_revisions_proposer_id'), table_name='revisions')
    op.drop_index(op.f('ix_revisions_created_at'), table_name='revisions')
    op.drop_index(op.f('ix_revisions_approver_id'), table_name='revisions')
    op.drop_table('revisions')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_sweet_name'), table_name='users')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_ctstage_name'), table_name='users')
    op.drop_index(op.f('ix_users_approval_group_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_articles_info_category'), table_name='articles')
    op.drop_index(op.f('ix_articles_article_pk'), table_name='articles')
    op.drop_index(op.f('ix_articles_article_number'), table_name='articles')
    op.drop_index(op.f('ix_articles_approval_group'), table_name='articles')
    op.drop_table('articles')
    op.drop_index(op.f('ix_info_categories_is_active'), table_name='info_categories')
    op.drop_table('info_categories')
    op.drop_index(op.f('ix_approval_groups_is_active'), table_name='approval_groups')
    op.drop_table('approval_groups')
    # ### end Alembic commands ###